UC 1 : Data Ingestion

In [1]:
import pandas as pd

# Load datasets
deliveries_df = pd.read_csv("data/deliveries.csv")
matches_df = pd.read_csv("data/matches.csv")

# Show first rows
print("Deliveries Data:")
display(deliveries_df.head())

print("Matches Data:")
display(matches_df.head())

Deliveries Data:

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

Matches Data:

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [2]:
# Shape
print("Deliveries Shape:", deliveries_df.shape)
print("Matches Shape:", matches_df.shape)

# Columns
print("\nDeliveries Columns:\n", deliveries_df.columns)
print("\nMatches Columns:\n", matches_df.columns)

# Data Types
print("\nDeliveries Info:")
print(deliveries_df.info())

print("\nMatches Info:")
print(matches_df.info())

Deliveries Shape: (260920, 17)
Matches Shape: (1095, 20)

Deliveries Columns:
 Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

Matches Columns:
 Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

Deliveries Info:
<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB
None

Matches Info:
<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB
None

UC 2 : Data Cleaning and Validation

Step 1: Check Missing Values

In [3]:
# Check missing values
print("Missing values in deliveries:\n")
print(deliveries_df.isnull().sum())

print("\nMissing values in matches:\n")
print(matches_df.isnull().sum())

Missing values in deliveries:

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

Missing values in matches:

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

Step 2: Handle Missing Values

In [8]:
# Matches dataset cleaning
matches_df['winner'] = matches_df['winner'].fillna("No Result")
matches_df['player_of_match'] = matches_df['player_of_match'].fillna("Unknown")
matches_df['city'] = matches_df['city'].fillna("Unknown")

# Deliveries dataset cleaning (UPDATED column names)
deliveries_df = deliveries_df.dropna(subset=['match_id', 'batter', 'bowler'])

Step 3: Fix Data type

In [9]:
# Convert IDs to int
deliveries_df['match_id'] = deliveries_df['match_id'].astype(int)
matches_df['id'] = matches_df['id'].astype(int)

# Ensure numeric columns
deliveries_df['total_runs'] = pd.to_numeric(deliveries_df['total_runs'])
deliveries_df['batsman_runs'] = pd.to_numeric(deliveries_df['batsman_runs'])

Step 4: Validate Match IDs

In [10]:
invalid_ids = set(deliveries_df['match_id']) - set(matches_df['id'])

print("Invalid Match IDs:", invalid_ids)

Invalid Match IDs: set()

Step 5: Remove Invalid Data

In [11]:
deliveries_df = deliveries_df[
    deliveries_df['match_id'].isin(matches_df['id'])
]

In [12]:
deliveries_df['player_dismissed'] = deliveries_df['player_dismissed'].fillna("None")

UC 3 : Data Transformation

STEP 1: Create Total Runs Column

In [13]:
# Recalculate total runs per ball
deliveries_df['calculated_total_runs'] = (
    deliveries_df['batsman_runs'] + deliveries_df['extra_runs']
)

# Check if matches existing total_runs
mismatch = (deliveries_df['total_runs'] != deliveries_df['calculated_total_runs']).sum()

print("Mismatch in total runs:", mismatch)

Mismatch in total runs: 0

STEP 2: Standardize Column Names

In [14]:
# Convert all columns to lowercase
deliveries_df.columns = deliveries_df.columns.str.lower()
matches_df.columns = matches_df.columns.str.lower()

STEP 3: Merge Both Datasets

In [15]:
# Merge deliveries with matches
merged_df = deliveries_df.merge(
    matches_df,
    left_on="match_id",
    right_on="id",
    how="inner"
)

print("Merged Data Shape:", merged_df.shape)
display(merged_df.head())

Merged Data Shape: (260920, 38)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

STEP 4: Clean After Merge

In [17]:
# Drop duplicate columns if needed
merged_df = merged_df.drop(columns=['id'], errors='ignore')

UC4 : Core Analysis